<?php
/**
 * AddonCouponTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Everyday\GmodStore\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * GmodStore
 *
 * Welcome to the Gmodstore API! You can use our API to access Gmodstore API endpoints, which can be used interact with Gmodstore programmatically.
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: unset
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Everyday\GmodStore\Sdk;

use PHPUnit\Framework\TestCase;

/**
 * AddonCouponTest Class Doc Comment
 *
 * @category    Class
 * @description AddonCoupon
 * @package     Everyday\GmodStore\Sdk
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class AddonCouponTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "AddonCoupon"
     */
    public function testAddonCoupon()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "code"
     */
    public function testPropertyCode()
    {
    }

    /**
     * Test attribute "percent"
     */
    public function testPropertyPercent()
    {
    }

    /**
     * Test attribute "max_uses"
     */
    public function testPropertyMaxUses()
    {
    }

    /**
     * Test attribute "expires_at"
     */
    public function testPropertyExpiresAt()
    {
    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "updated_at"
     */
    public function testPropertyUpdatedAt()
    {
    }

    /**
     * Test attribute "addon"
     */
    public function testPropertyAddon()
    {
    }
}
