<?php
/**
 * AdventCalendarStatsTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Everyday\GmodStore\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * GmodStore API
 *
 * Welcome to the GmodStore API! You can use our API to access GmodStore API endpoints, which can be used interact with GmodStore programmatically.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: unset
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Everyday\GmodStore\Sdk;

use PHPUnit\Framework\TestCase;

/**
 * AdventCalendarStatsTest Class Doc Comment
 *
 * @category    Class
 * @description AdventCalendarStats
 * @package     Everyday\GmodStore\Sdk
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class AdventCalendarStatsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "AdventCalendarStats"
     */
    public function testAdventCalendarStats()
    {
    }

    /**
     * Test attribute "squaresOpened"
     */
    public function testPropertySquaresOpened()
    {
    }

    /**
     * Test attribute "addonsAwarded"
     */
    public function testPropertyAddonsAwarded()
    {
    }

    /**
     * Test attribute "couponsAwarded"
     */
    public function testPropertyCouponsAwarded()
    {
    }
}
