<?php
/**
 * AddonCouponsApiTest
 * PHP version 7.2
 *
 * @category Class
 * @package  Everyday\GmodStore\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * GmodStore
 *
 * Welcome to the Gmodstore API! You can use our API to access Gmodstore API endpoints, which can be used interact with Gmodstore programmatically.
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: unset
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Everyday\GmodStore\Sdk;

use \Everyday\GmodStore\Sdk\Configuration;
use \Everyday\GmodStore\Sdk\ApiException;
use \Everyday\GmodStore\Sdk\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * AddonCouponsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Everyday\GmodStore\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AddonCouponsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createAddonCoupon
     *
     * Create an addon coupon.
     *
     */
    public function testCreateAddonCoupon()
    {
    }

    /**
     * Test case for deleteAddonCoupon
     *
     * Destroy an addon's coupon.
     *
     */
    public function testDeleteAddonCoupon()
    {
    }

    /**
     * Test case for getAddonCoupon
     *
     * Fetch an addon's coupon.
     *
     */
    public function testGetAddonCoupon()
    {
    }

    /**
     * Test case for listAddonCoupons
     *
     * Fetch all the coupons for an addon.
     *
     */
    public function testListAddonCoupons()
    {
    }

    /**
     * Test case for updateAddonCoupon
     *
     * Update an addon's coupon.
     *
     */
    public function testUpdateAddonCoupon()
    {
    }
}
