<?php
/**
 * AddonPurchasesApiTest
 * PHP version 7.2
 *
 * @category Class
 * @package  Everyday\GmodStore\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * GmodStore
 *
 * Welcome to the Gmodstore API! You can use our API to access Gmodstore API endpoints, which can be used interact with Gmodstore programmatically.
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: unset
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Everyday\GmodStore\Sdk;

use \Everyday\GmodStore\Sdk\Configuration;
use \Everyday\GmodStore\Sdk\ApiException;
use \Everyday\GmodStore\Sdk\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * AddonPurchasesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Everyday\GmodStore\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AddonPurchasesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createAddonPurchase
     *
     * Create a purchase for an addon.
     *
     */
    public function testCreateAddonPurchase()
    {
    }

    /**
     * Test case for getAddonPurchase
     *
     * Get a purchase of an addon by user.
     *
     */
    public function testGetAddonPurchase()
    {
    }

    /**
     * Test case for listAddonPurchases
     *
     * Fetch all purchases of an addon.
     *
     */
    public function testListAddonPurchases()
    {
    }

    /**
     * Test case for updateAddonPurchase
     *
     * Update a purchase for an addon.
     *
     */
    public function testUpdateAddonPurchase()
    {
    }
}
